services:
  # NOTE: User Service
  user-service:
    build: ./services/user-service
    ports:
      - "5001:5000"
    depends_on:
      user_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_USER_URL}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - parfummelier-network

  # NOTE: Authentication Service
  authentication-service:
    build: ./services/authentication-service/
    ports:
      - "5002:5000"
    depends_on:
      user_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_USER_URL}
      - SECRET_KEY=${SECRET_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - parfummelier-network

  # NOTE: Product Service
  product-service:
    build: ./services/product-service/
    ports:
      - "5003:5000"
    depends_on:
      product_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_PRODUCT_URL}
      - API_BASE_URL=${PRODUCT_API_URL}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./services/product-service/images:/app/images
    networks:
      - parfummelier-network
  # NOTE: Quiz Service
  quiz-service:
    build: ./services/quiz-service/
    ports:
      - "5005:5000"
    networks:
      - parfummelier-network
    depends_on:
      - product-service

  # NOTE: Api Gateway
  api-gateway:
    build: ./api-gateway/
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001" # Expose Admin API for local access
    depends_on:
      - user-service
      - authentication-service
      - product-service
      - quiz-service
      - forum-service
    volumes:
      # - ./api-gateway/kong.yml:/app/kong.yml
      - ./api-gateway/kong.yml:/etc/kong/kong.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    networks:
      - parfummelier-network

  # NOTE: USER_DB
  user_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USER_DB}
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_USER_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - parfummelier-network

  # NOTE: PRODUCT_DB
  product_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PRODUCT_DB}
    ports:
      - "5433:5432" # Expose different port for product database
    volumes:
      - products_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PRODUCT_DB}",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - parfummelier-network
  # NOTE: FORUM DB for storing Post, Comment, and Thread
  forum_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_FORUM_DB}
    ports:
      - "5435:5432" # New port to avoid conflicts
    volumes:
      - forum_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_FORUM_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - parfummelier-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${SECRET_KEY}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_PRODUCT_API_BASE_URL=${NEXT_PUBLIC_PRODUCT_API_BASE_URL}
    networks:
      - parfummelier-network
    depends_on:
      - api-gateway

  # NOTE: Forum Service
  forum-service:
    build: ./services/forum-service
    ports:
      - "5004:5000" # Expose the forum service on port 5004
    depends_on:
      - mongo
      - forum_db
    environment:
      - MONGO_URI=mongodb://mongo:27017/chat_database
      - SECRET_KEY=${SECRET_KEY}
      - USER_SERVICE_URL=http://user-service:5000
      - POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@forum_db:5432/${POSTGRES_FORUM_DB}
    networks:
      - parfummelier-network

  # NOTE: MongoDB service (for storing chat data)
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Expose the default MongoDB port
    networks:
      - parfummelier-network
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  parfummelier-network:
    driver: bridge

volumes:
  user_data:
  products_data:
  mongo_data:
  forum_data:
    driver: local
