import pytest
import requests

# Sample scent bank data that would be generated by quiz-service
scent_bank_data = {
    "accordbank": ["Woody", "Amber"]  # Mock accords the user liked
}

@pytest.fixture(scope="module")
def base_url():
    # Use the actual product-service URL or a mocked one for testing
    return "http://product-service:5001"

def test_integration_quiz_to_product_service(base_url):
    # Assuming `quiz-service` collected a scent bank, now send it to `product-service`
    response = requests.post(f"{base_url}/recommendations", json=scent_bank_data)
    
    # Verify if `product-service` returns correct recommendations
    assert response.status_code == 200  # Ensure successful response
    
    recommendations = response.json().get("recommendations", [])
    
    # Check if recommendations contain expected products with "Woody" or "Amber" accords
    assert any("Woody" in product["accords"] for product in recommendations), "Expected accord not found"
    assert any("Amber" in product["accords"] for product in recommendations), "Expected accord not found"
